development:
  facebook_app_id: #118981661496259
  twitter_login: #dekart1234
  google_analytics_id: #UA-111105-32
  google_share: #true

production:
  facebook_app_id: 709120592446892
  twitter_login: dekart1234
  google_analytics_id: UA-111105-32